import { type ReactNode } from "react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { HomeIcon, Pencil1Icon } from "@radix-ui/react-icons";
import clsx from "clsx";

export function useMainLayout(children: ReactNode) {
  const router = useRouter();
  const items = [
    {
      icon: <HomeIcon className="h-6 w-6" />,
      href: "/home",
      text: "Home",
    },
    {
      icon: <Pencil1Icon className="h-6 w-6" />,
      href: "/post",
      text: "Create Post",
    },
  ];

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid h-full w-full grid-cols-1 gap-6 bg-slate-950 px-10 py-20 text-white lg:grid-cols-2 xl:grid-cols-[0.8fr_1fr_0.8fr]">
        <div className="ml-auto flex w-full max-w-[400px] flex-col gap-3">
          <h1 className="text-xl font-bold tracking-tight sm:text-3xl">
            Shark <span className="text-pink-400">Post</span>
          </h1>
          {items.map((item) => (
            <Link
              key={item.href}
              href={item.href}
              className={clsx(
                "flex flex-row items-center gap-2 rounded-lg px-4 py-2 text-xl font-semibold",
                router.route.startsWith(item.href) && "bg-slate-900",
              )}
            >
              {item.icon}
              {item.text}
            </Link>
          ))}
        </div>
        {children}
        <div />
      </main>
    </>
  );
}
