import { type ReactNode } from "react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import {
  AvatarIcon,
  HeartIcon,
  HomeIcon,
  Pencil1Icon,
} from "@radix-ui/react-icons";
import clsx from "clsx";

import "draft-js/dist/Draft.css";
import { setModal } from "~/stores/modal";

export function useMainLayout(children: ReactNode) {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={clsx(
          "mx-auto grid h-full w-full max-w-screen-2xl grid-cols-[auto_1fr] gap-3 p-3 text-white",
          "md:gap-6 md:p-10 lg:grid-cols-[0.4fr_1fr_0.4fr]",
        )}
      >
        <Sidebar />
        {children}
        <div />
      </main>
    </>
  );
}

function Sidebar() {
  const router = useRouter();
  const items = [
    {
      icon: <HomeIcon className="h-6 w-6" />,
      href: "/home",
      text: "Home",
    },
    {
      icon: <HeartIcon className="h-6 w-6" />,
      href: "/favourite",
      text: "Favourite",
    },
    {
      icon: <AvatarIcon className="h-6 w-6" />,
      href: "/account",
      text: "Account",
    },
  ];

  return (
    <div className="flex flex-col gap-3 md:min-w-[250px]">
      <h1 className="text-xl font-bold tracking-tight max-md:hidden sm:text-3xl">
        Shark <span className="text-pink-400">Post</span>
      </h1>
      {items.map((item) => (
        <Link
          key={item.href}
          href={item.href}
          className={clsx(
            "flex flex-row items-center gap-2 rounded-lg px-4 py-2 text-xl transition-colors",
            "hover:bg-slate-900",
            router.route.startsWith(item.href) && "bg-slate-900 font-semibold",
          )}
        >
          {item.icon}
          <span className="max-md:hidden">{item.text}</span>
        </Link>
      ))}
      <button
        className="mt-8 w-full rounded-full bg-pink-400 px-4 py-2 text-center text-lg font-semibold"
        onClick={() => setModal("create-post", true)}
      >
        <Pencil1Icon className="h-6 w-6 md:hidden" />
        <span className="max-md:hidden">Create Post</span>
      </button>
    </div>
  );
}
